__version__ = "0.14.0"
__kubernetes_plugin_version__ = "v0.7.0"
__rkt_plugin_version__ = "v0.1.0"
__libnetwork_plugin_version__ = "v0.7.0"
__libcalico_version__ = "v0.9.0"
__felix_version__ = "1.3.0a6"
