FROM jeanblanchard/alpine-glibc
MAINTAINER Tom Denham <tom@projectcalico.org>

ADD dist/calicoctl ./calicoctl
ADD test-data/default-ippool.yaml ./ippool.yaml

ENV CALICO_CTL_CONTAINER=TRUE

# libltdl.so is needed by docker command line tool
RUN apk add --no-cache libltdl

ENTRYPOINT ["./calicoctl"]
