#!/bin/sh
exec 2>&1
sed "s/HOSTNAME/$HOSTNAME/" /etc/calico/confd/templates/bird_aggr.toml.template > /etc/calico/confd/conf.d/bird_aggr.toml
sed "s/HOSTNAME/$HOSTNAME/" /etc/calico/confd/templates/bird6_aggr.toml.template > /etc/calico/confd/conf.d/bird6_aggr.toml
# ETCD_ENDPOINTS overrides ETCD_SCHEME / ETCD_AUTHORITY, if present
case "$ETCD_ENDPOINTS" in
    # https matches *http* as well.
    *http*)  ETCD_NODE=${ETCD_ENDPOINTS}
             ;;
    *)       ETCD_NODE=${ETCD_SCHEME:=http}://${ETCD_AUTHORITY}
             ;;
esac
exec confd -confdir=/etc/calico/confd -interval=5 -watch --log-level=debug \
           -node $ETCD_NODE -client-key=${ETCD_KEY_FILE} \
           -client-cert=${ETCD_CERT_FILE} -client-ca-keys=${ETCD_CA_CERT_FILE}
